- test/org/sbml/jsbml/test/PackageVersionTests.java
Small change made with Anton to show him how pull request work on github.
> Removed package req from the tests.

- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialCompartmentPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialModelPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/xml/parsers/SpatialParser.java
These 2 classes have been tested and also the parser has been updated accordingly.
> SpatialModelPluginConstraints and SpatialCompartmentPluginConstraints

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CompartmentMapping.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/Geometry.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/SpatialConstants.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/BoundaryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CompartmentMappingConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/DomainTypeConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/GeometryDefinitionConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/InteriorPointConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialCompartmentPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialModelPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialParameterPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialReactionPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialSpeciesPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/xml/parsers/SpatialParser.java
Made the required changes in documentation.
Added handling of MixedGeometry element.
Finalized CompartmentMappingConstraints (tested).
Modified Geometry class to include getters for ListOf<?> elements.
> Implement spatial-213XX and minor fixes.

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/AdjacentDomains.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CoordinateComponent.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AdjacentDomainsConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CompartmentMappingConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CoordinateComponentConstraints.java
Finalize AdjacentDomains constraints.
Finalize CoordinateComponent constraints.
Modified test files for spatial-21406:
https://drive.google.com/drive/folders/1xxdq5SeDYccDbBqZOwYh7UWTI0-wj17u?usp=sharing
Modifications include check of base units and user defined units.
> Implement Spatial-211XX and Spatial-214XX

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/AnalyticVolume.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AdjacentDomainsConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AnalyticVolumeConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/BoundaryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CompartmentMappingConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CoordinateComponentConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/DomainTypeConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/GeometryDefinitionConstraints.java
I will upload the modified test files for 21904 and 21907 in the head folder and update in this thread.
> Implement 219XX and modify existing constraints to check 'spatial:name' attribute.

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/AnalyticGeometry.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/Domain.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/SpatialConstants.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AnalyticGeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/DomainConstraints.java
Implemented:
DomainConstraints
AnalyticGeometryConstraints
Modified tests for rule spatial-20806 have been added to the head folder.
> Implement rules 208XX and 218XX

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/SampledFieldGeometry.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AdjacentDomainsConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AdvectionCoefficientConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AnalyticGeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AnalyticVolumeConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/BoundaryConditionConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/BoundaryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CompartmentMappingConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CoordinateComponentConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/DiffusionCoefficientConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/DomainConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/DomainTypeConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/GeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/GeometryDefinitionConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/InteriorPointConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SampledFieldGeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialCompartmentPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialModelPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialParameterPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialReactionPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialSpeciesPluginConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialSymbolReferenceConstraints.java
I had already pushed the SampledFieldGeometryConstraints to the branch before seeing the message, so it got added to this PR.
Maybe the constraint file can be checked by viewing the commits I think.
Sorry for the inconvenience! :sweat_smile:
> Implement 215XX and formatting changes.

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CSGeometry.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/SampledVolume.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SampledVolumeConstraints.java
Implements constraints for:
SampledVolume
CSGeometry
Modified test files for 21705 and 222XX uploaded to head folder.
> Implement Rules Spatial-217XX and Spatial-222XX

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CSGObject.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CSGTranslation.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGObjectConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGTranslationConstraints.java
Implement constraints for:
CSGObject
CSGTranslation
Modified test files uploaded to the head folder.
> Implement rules 223XX and 226XX

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CSGRotation.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CSGScale.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/SpatialConstants.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGRotationConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGScaleConstraints.java
Implemented constraints for:
CSGRotation
CSGScale
Made changes in `SpatialConstants.java` to conform with the latest specification. 
Also modified `CSGRotation.java` to reflect these changes. Modified method names
to agree with the attribute names.
Modified test files uploaded to head folder.
> Implement rules 227XX and 228XX

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CSGHomogeneousTransformation.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/TransformationComponent.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGHomogeneousTransformationConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/TransformationComponentConstraints.java
Implemented constraints for:
CSGHomogeneousTransformation
TransformationComponent
Modified TransformationComponent class to read and set the componentsLength attribute.
Register TransformationComponent elements as a child in CSGHomogeneousTransformation.
Modified test files uploaded.
> Implement rules 229XX and 230XX

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CSGPrimitive.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/CSGSetOperator.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/ParametricGeometry.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGPrimitiveConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGSetOperatorConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/ParametricGeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/xml/parsers/SpatialParser.java
Implemented constraints for:
CSGPrimitive
CSGSetOperator
ParametricGeometry
Modifies test files uploaded.
> Implement rules 231XX and 232XX

- extensions/spatial/src/org/sbml/jsbml/ext/spatial/OrdinalMapping.java
- extensions/spatial/src/org/sbml/jsbml/ext/spatial/SampledField.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/OrdinalMappingConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SampledFieldConstraints.java
- extensions/spatial/src/org/sbml/jsbml/xml/parsers/SpatialParser.java
Implemented constraints for:
OrdinalMapping
SampledField
Modified test files uploaded.
This PR concludes implementing the rules provided in the 
spatial package specification draft 0.94
> Implement rules 239XX and 216XX

- core/src/org/sbml/jsbml/validator/offline/factory/SBMLErrorCodes.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/AnalyticGeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/BoundaryConditionConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGSetOperatorConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/CSGeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/DiffusionCoefficientConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/DomainTypeConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/GeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/MixedGeometryConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SampledFieldConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SampledVolumeConstraints.java
- extensions/spatial/src/org/sbml/jsbml/validator/offline/constraints/SpatialReactionPluginConstraints.java
Implemented new rules:
SPATIAL_20650
SPATIAL_20750 - SPATIAL_20752
SPATIAL_21650 - SPATIAL_21652
SPATIAL_21750 - SPATIAL_21754
SPATIAL_21950
SPATIAL_22350
SPATIAL_23250 - SPATIAL_23251
SPATIAL_23450 - SPATIAL_23452
SPATIAL_23650
SPATIAL_23750 - SPATIAL_23754
SPATIAL_23850
> Implement newly added rules.

- extensions/fbc/src/org/sbml/jsbml/ext/fbc/converters/FbcV2ToFbcV1Converter.java
Change the handling of lowerBound and upperBound deletion during conversion from v2 to v1 to be deleted after all reactions have been processed.
> Pivotal 161592475

- extensions/comp/resources/testGathering/internalise_online_chain.xml
- extensions/comp/resources/testGathering/online_chain_and_relative.xml
- extensions/comp/resources/testGathering/online_chain_online.xml
- extensions/comp/resources/testGathering/simple_online_url.xml
- extensions/comp/src/org/sbml/jsbml/ext/comp/ExternalModelDefinition.java
- extensions/comp/src/org/sbml/jsbml/ext/comp/util/CompFlatteningConverter.java
- extensions/comp/test/org/sbml/jsbml/ext/comp/test/CompFlattenTest.java
- extensions/comp/test/org/sbml/jsbml/ext/comp/test/TestExternalModelDefinition.java
[story #140483535](https://www.pivotaltracker.com/story/show/140483535)
> Vetter comp single file

- extensions/render/src/org/sbml/jsbml/ext/render/Ellipse.java
- extensions/render/src/org/sbml/jsbml/ext/render/RelAbsVector.java
- extensions/render/test/org/sbml/jsbml/ext/render/test/EllipseTest.java
Implemented the changes discussed in the Hangout, which are currently still missing from master.
> Check render

- README.md
- codemeta.json
This updates some dates and numbers in `README.md` and `codemeta.json`.
> Update readme & codemeta.json

- core/src/org/sbml/jsbml/xml/XMLNamespaces.java
- core/src/org/sbml/jsbml/xml/XMLNode.java
- doc/announcements/jsbml-1.5-release-announcement.md
Some suggested edits to the text of the announcement
> Minor edits to announcement

- README.md
> Upgraded version link in Readme.md

- core/pom.xml
This should fix the security issue https://github.com/sbmlteam/jsbml/security/dependabot/20.
> Udate of com.thoughtworks.xstream:xstream
